### ISSUE TITLE
[Firefox issue] The text and the symbol of the subscribed button look brighter than it should.

### ISSUE THREAD

**Issue by LautaroL20** [omnidevZero/YouTubeRedux#128]
In Firefox, the word "subscribed" and the "bell" symbol of the subscribed button looks brighter than it should. 

**Here is a comparison of how it currently looks, and how it should actually look:**

![208232493-21272f31-eb38-4f0e-aa63-e04390cb8d55](https://user-images.githubusercontent.com/12244376/209823890-b818973a-fc58-4971-9095-ae4a9eb66bbe.png)

**Comment by omnidevZero** [comment]
Text and notification bell colors will be fixed in the upcoming update, however, the bell button's background will stay as it is, so brighter than the subs count. That's because functionality-wise it now makes sense since the text and the bell are now both a part of the same button invoking the same action and also because of the hacky way  I used to move the bell button to the right edge of its container which makes modifying it separately quite painful now.
