### ISSUE TITLE
Home page almost identical after reload

### ISSUE THREAD

**Issue by znopp** [omnidevZero/YouTubeRedux#15]
Just like the title says, whenever I go to the homepage it loads in videos, but upon pressing the logo / F5 it displays almost exactly the same videos. This can happen with hours of time in between each reload.

Ex:[https://cdn.znopp.pw/IukQia.mp4](url) (znopp.pw is my personal webserver for uploading things)

I'm not entirely sure why this is happening, as without this extension I could reload the page at the rate seen in this video and get completely new videos recommended to me.

**Comment by znopp** [comment]
Can also confirm that the home page stays the same even after watching a video and going back to the homepage (without pressing F5). Currently, a 3-hour old video by LTT still says, after having watched it and many other videos and then pressing the youtube button, that it is 25 minutes old.

**Comment by znopp** [comment]
In a private window where the extension is not allowed to run, pressing the youtube button does refresh the

**Comment by omnidevZero** [comment]
Thanks for the report. This happens because of the homepage fix setting that's needed to properly display more than 4 items per row there. Homepage isn't properly reloaded in that case because I'm hiding the original grid with videos and putting these in another container which isn't handled in any way by YouTube, which includes clicking the logo. I'll try to have it fixed soon.

**Comment by znopp** [comment]
It now works! Thanks for fixing the issue :)
