### ISSUE TITLE
White seam at the top of every Youtube page in Dark Theme

### ISSUE THREAD

**Issue by Nicholas-Steel** [omnidevZero/YouTubeRedux#61]
https://imgur.com/EHRDNsl

Firefox 104.0.x
Windows 10 21H2
Tested disabling all other Youtube addons.

**Comment by KingGamingYT** [comment]
This has happened to me before, it usually goes away after a video loads or a page reload. Is it just stuck there?

**Comment by omnidevZero** [comment]
Thanks, will be fixed in the next update!

It appears that for some reason if channel page is the first page you enter in dark theme, the top bar wont have the "dark" attribute which I'm checking for when applying the bottom border so it's color is inherited from the light theme. However, if you first land on the video page and then navigate to the channel page, the attribute will be properly applied and the issue won't occur. So it looks like a YT issue but I can change the CSS selectors so it won't matter.

**Comment by Nicholas-Steel** [comment]
Interesting, thanks for the explanation of what is causing it.
