### ISSUE TITLE
Custom resolution doesn't appear to do much.

### ISSUE THREAD

**Issue by Lannuked** [omnidevZero/YouTubeRedux#7]
I went into the dropdown and selected "Custom" for the resolution, and it doesn't appear to give me an option to modify it. I want to try to change the aspect ratio to 4:3.

**Comment by omnidevZero** [comment]
Selecting "Custom" should result in displaying a browser prompt pop-up. Check if you don't have them blocked globally somehow. Thing is even if that works you won't be able to (easily) change it to 4:3 ratio because width is automatically calculated based on specified height and your screen's aspect ratio. So you would have to go through a wonky workaround and first change your actual screen resolution to use any 4:3 setting and then change the custom resolution in Redux.
Expect issues though. I guess there was a reason why I made it this way ;)
