### ISSUE TITLE
"Open Description" button not working?

### ISSUE THREAD

**Issue by dvcky** [omnidevZero/YouTubeRedux#8]
Self explanatory, I click "Open Description" and nothing additional loads. The text changes to "Close Description", as shown below, but nothing is actually added.

![2021-12-22_00-02](https://user-images.githubusercontent.com/15352128/147043921-d0378e0e-6d20-4978-a288-f1563312876c.png)

If it helps, here's what I'm using:

- the Chrome Web Store version of the extension (2.11.6)
- Brave Browser (1.33.106), Chromium (96.0.4664.110)

Since Brave has a built-in ad/script blocker, I tried disabling that as well as all of my other extensions. None of this worked, **however enabling it as the only extension in Private Browsing mode works**. Any idea how to fix this?

**Comment by omnidevZero** [comment]
If you enabled hiding chat via "Hide stuff" section of settings try unchecking that. "Show description" should display description in a window to the right of video that looks similar to chat window and it's possible Redux is picking that up instead and hiding it when hiding chat is enabled.
I'm not able to test it because it appears the change is in staged rollout and only selected group of users got it until now - me excluded. This might be why it works correctly in Private Browsing mode as you're most likely signed out there and the change isn't applied (since it's account based).

I'll try restoring it to the previous "Show more" behavior but first I have to get the change myself.

**Comment by dvcky** [comment]
Apologies, I should have clarified, this applies on any video - stream or not (I can imagine having another chat in my issue confuses things). I checked my settings, and I'm not hiding collapsed chat. I tried enabling and disabling that, but to no avail.

You are probably right about the layout change though, I didn't even think about that. Interestingly, when I log out on my non-private browsing mode, a different artifact appears. The traditional "video info" is completely gone and replaced. It's like an element from normal YouTube didn't get picked up by the extension. That is probably a similar issue (since it's a pretty new layout change), but I'm not sure since I am logged out in this case. Here's what that looks like:

![image](https://user-images.githubusercontent.com/15352128/147363888-5ff6fb1a-d4ba-4b4f-b6a7-75e82019ecb1.png)
